"""department settings

Revision ID: 30154abbfc42
Revises: 902bbcb42eb9
Create Date: 2026-08-20 21:20:38.555433
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '30154abbfc42'
down_revision = '902bbcb42eb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('IQC', 'OQC', 'FIELD', name='department', native_enum=False, length=16), nullable=False),
    sa.Column('chart_titles', sa.JSON(), nullable=False),
    sa.Column('table_titles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department', name='uq_department_settings')
    )
    with op.batch_alter_table('department_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_settings_department'), ['department'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_settings_department'))

    op.drop_table('department_settings')
    # ### end Alembic commands ###
