"""version snapshot summary

Revision ID: 30dc23811a58
Revises: 61fa509752f2
Create Date: 2026-08-19 22:12:34.593753
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '30dc23811a58'
down_revision = '61fa509752f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentation_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('warnings', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentation_versions', schema=None) as batch_op:
        batch_op.drop_column('warnings')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
