"""report blocks from the workbook

Revision ID: 5af291c4e799
Revises: 7696dbad9dc7
Create Date: 2026-08-20 17:45:28.441589
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '5af291c4e799'
down_revision = '7696dbad9dc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_data_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=160), nullable=False),
    sa.Column('source_range', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('paragraphs', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['department_data_id'], ['department_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_blocks_department_data_id'), ['department_data_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_blocks_department_data_id'))

    op.drop_table('report_blocks')
    # ### end Alembic commands ###
