"""no generated analysis on issues

Revision ID: 7696dbad9dc7
Revises: c9887591ff65
Create Date: 2026-08-20 17:13:35.525226
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision = '7696dbad9dc7'
down_revision = 'c9887591ff65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('analytical_severity')
        batch_op.drop_column('trend')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trend', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('analytical_severity', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
