"""row block and inferred fields

Revision ID: 975dfca50c90
Revises: 30dc23811a58
Create Date: 2026-08-20 06:41:53.106000
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '975dfca50c90'
down_revision = '30dc23811a58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('inferred', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_rows', schema=None) as batch_op:
        batch_op.drop_column('inferred')
        batch_op.drop_column('block')

    # ### end Alembic commands ###
