"""issue reports

Revision ID: c9887591ff65
Revises: 975dfca50c90
Create Date: 2026-08-20 13:19:30.257068
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c9887591ff65'
down_revision = '975dfca50c90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('IQC', 'OQC', 'FIELD', name='department', native_enum=False, length=16), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=True),
    sa.Column('period', sa.JSON(), nullable=True),
    sa.Column('reference_period', sa.JSON(), nullable=True),
    sa.Column('table_name', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('subcategory', sa.String(length=160), nullable=True),
    sa.Column('metric', sa.String(length=160), nullable=True),
    sa.Column('series_type', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description_doc', sa.JSON(), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('translation_key', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', name='issueseverity', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='issuestatus', native_enum=False, length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('delta_percent', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('analytical_severity', sa.String(length=10), nullable=True),
    sa.Column('trend', sa.JSON(), nullable=True),
    sa.Column('source_cell', sa.String(length=12), nullable=True),
    sa.Column('source_range', sa.String(length=40), nullable=True),
    sa.Column('origin', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['presentation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_department'), ['department'], unique=False)
        batch_op.create_index('ix_issues_scope', ['version_id', 'period_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_translation_key'), ['translation_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_version_id'), ['version_id'], unique=False)

    op.create_table('issue_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_media_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_media_issue_id'))

    op.drop_table('issue_media')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_version_id'))
        batch_op.drop_index(batch_op.f('ix_issues_translation_key'))
        batch_op.drop_index(batch_op.f('ix_issues_status'))
        batch_op.drop_index('ix_issues_scope')
        batch_op.drop_index(batch_op.f('ix_issues_department'))

    op.drop_table('issues')
    # ### end Alembic commands ###
