"""initial schema

Revision ID: e1147da3d1bd
Revises: 
Create Date: 2026-08-19 20:19:45.421776
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e1147da3d1bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_sha256'), ['sha256'], unique=True)

    op.create_table('presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('IQC', 'OQC', 'FIELD', name='department', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('period_label', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'ARCHIVED', 'TRASHED', name='presentationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('trashed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presentations_department'), ['department'], unique=False)

    op.create_table('raw_data_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('IQC', 'OQC', 'FIELD', name='department', native_enum=False, length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_data_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_data_files_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_data_files_sha256'), ['sha256'], unique=False)

    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('source_preview', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', 'target_language', 'provider', name='uq_translation')
    )
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.create_index('ix_translations_lookup', ['source_hash', 'target_language'], unique=False)

    op.create_table('department_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('IQC', 'OQC', 'FIELD', name='department', native_enum=False, length=16), nullable=False),
    sa.Column('raw_data_file_id', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['raw_data_file_id'], ['raw_data_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_data_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_data_raw_data_file_id'), ['raw_data_file_id'], unique=False)

    op.create_table('presentation_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='versionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['presentation_versions.id'], ),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presentation_id', 'number', name='uq_version_number')
    )
    with op.batch_alter_table('presentation_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presentation_versions_presentation_id'), ['presentation_id'], unique=False)

    op.create_table('issue_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('IQC', 'OQC', 'FIELD', name='department', native_enum=False, length=16), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['presentation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_reports_version_id'), ['version_id'], unique=False)

    op.create_table('table_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_data_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=160), nullable=False),
    sa.Column('source_range', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('department', sa.String(length=16), nullable=True),
    sa.Column('hierarchy', sa.JSON(), nullable=False),
    sa.Column('shape', sa.String(length=16), nullable=False),
    sa.Column('period_axis', sa.String(length=16), nullable=False),
    sa.Column('header_row_count', sa.Integer(), nullable=False),
    sa.Column('label_col_count', sa.Integer(), nullable=False),
    sa.Column('merged_ranges', sa.JSON(), nullable=False),
    sa.Column('styles', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['department_data_id'], ['department_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_definitions_department_data_id'), ['department_data_id'], unique=False)

    op.create_table('version_imports',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('department_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_data_id'], ['department_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['presentation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'department_data_id')
    )
    op.create_table('chart_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('table_definition_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['table_definition_id'], ['table_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['presentation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chart_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_definitions_version_id'), ['version_id'], unique=False)

    op.create_table('issue_report_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_report_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('align', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['issue_report_id'], ['issue_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_report_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_report_columns_issue_report_id'), ['issue_report_id'], unique=False)

    op.create_table('issue_report_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_report_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['issue_report_id'], ['issue_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_report_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_report_rows_issue_report_id'), ['issue_report_id'], unique=False)

    op.create_table('table_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_definition_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('col_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('semantic', sa.String(length=16), nullable=False),
    sa.Column('value_type', sa.String(length=10), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('number_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('display_value', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('number_format', sa.String(length=80), nullable=True),
    sa.Column('display', sa.JSON(), nullable=True),
    sa.Column('style_id', sa.String(length=20), nullable=True),
    sa.Column('source_address', sa.String(length=12), nullable=True),
    sa.Column('merged_range', sa.String(length=24), nullable=True),
    sa.Column('is_merge_anchor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_definition_id'], ['table_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_cells', schema=None) as batch_op:
        batch_op.create_index('ix_table_cells_position', ['table_definition_id', 'row_index', 'col_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_cells_table_definition_id'), ['table_definition_id'], unique=False)

    op.create_table('table_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_definition_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('source_column', sa.String(length=8), nullable=True),
    sa.Column('header_path', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('period', sa.JSON(), nullable=True),
    sa.Column('series', sa.String(length=60), nullable=True),
    sa.Column('semantic', sa.String(length=16), nullable=False),
    sa.Column('is_label_column', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['table_definition_id'], ['table_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_definition_id', 'index', name='uq_table_column')
    )
    with op.batch_alter_table('table_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_columns_table_definition_id'), ['table_definition_id'], unique=False)

    op.create_table('table_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_definition_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('label_path', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('subcategory', sa.String(length=160), nullable=True),
    sa.Column('metric', sa.String(length=160), nullable=True),
    sa.Column('semantic', sa.String(length=16), nullable=False),
    sa.Column('is_header_row', sa.Boolean(), nullable=False),
    sa.Column('period', sa.JSON(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['table_definition_id'], ['table_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_definition_id', 'index', name='uq_table_row')
    )
    with op.batch_alter_table('table_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_rows_table_definition_id'), ['table_definition_id'], unique=False)

    op.create_table('issue_report_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_report_id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('doc', sa.JSON(), nullable=False),
    sa.Column('align', sa.String(length=10), nullable=False),
    sa.Column('valign', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['issue_report_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_report_id'], ['issue_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['issue_report_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'column_id', name='uq_issue_cell')
    )
    with op.batch_alter_table('issue_report_cells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_report_cells_issue_report_id'), ['issue_report_id'], unique=False)

    op.create_table('asset_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cell_id'], ['issue_report_cells.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['presentation_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'cell_id', name='uq_asset_usage')
    )
    with op.batch_alter_table('asset_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_usages_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_usages_cell_id'), ['cell_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_usages_cell_id'))
        batch_op.drop_index(batch_op.f('ix_asset_usages_asset_id'))

    op.drop_table('asset_usages')
    with op.batch_alter_table('issue_report_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_report_cells_issue_report_id'))

    op.drop_table('issue_report_cells')
    with op.batch_alter_table('table_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_rows_table_definition_id'))

    op.drop_table('table_rows')
    with op.batch_alter_table('table_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_columns_table_definition_id'))

    op.drop_table('table_columns')
    with op.batch_alter_table('table_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_cells_table_definition_id'))
        batch_op.drop_index('ix_table_cells_position')

    op.drop_table('table_cells')
    with op.batch_alter_table('issue_report_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_report_rows_issue_report_id'))

    op.drop_table('issue_report_rows')
    with op.batch_alter_table('issue_report_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_report_columns_issue_report_id'))

    op.drop_table('issue_report_columns')
    with op.batch_alter_table('chart_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_definitions_version_id'))

    op.drop_table('chart_definitions')
    op.drop_table('version_imports')
    with op.batch_alter_table('table_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_definitions_department_data_id'))

    op.drop_table('table_definitions')
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_reports_version_id'))

    op.drop_table('issue_reports')
    with op.batch_alter_table('presentation_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presentation_versions_presentation_id'))

    op.drop_table('presentation_versions')
    with op.batch_alter_table('department_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_data_raw_data_file_id'))
        batch_op.drop_index(batch_op.f('ix_department_data_department'))

    op.drop_table('department_data')
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_index('ix_translations_lookup')

    op.drop_table('translations')
    with op.batch_alter_table('raw_data_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_data_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_raw_data_files_department'))

    op.drop_table('raw_data_files')
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presentations_department'))

    op.drop_table('presentations')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_sha256'))

    op.drop_table('assets')
    # ### end Alembic commands ###
